name: Android Build (APK)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Gradle 7.6
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Patch gradle-plugin build.gradle.kts for warningsAsErrors bug
        run: |
          sed -i'' 's/allWarningsAsErrors =/allWarningsAsErrors.set(/' node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/build.gradle.kts
          sed -i'' 's/^\( *project\.properties\["enableWarningsAsErrors"\].*\)$/\1)/' node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/build.gradle.kts
          sed -i'' 's/allWarningsAsErrors =/allWarningsAsErrors.set(/' node_modules/@react-native/gradle-plugin/settings-plugin/build.gradle.kts
          sed -i'' 's/^\( *project\.properties\["enableWarningsAsErrors"\].*\)$/\1)/' node_modules/@react-native/gradle-plugin/settings-plugin/build.gradle.kts
          cat node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/build.gradle.kts | grep allWarningsAsErrors || true
          cat node_modules/@react-native/gradle-plugin/settings-plugin/build.gradle.kts | grep allWarningsAsErrors || true

      - name: Build Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease
        env:
          enableWarningsAsErrors: false

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk 