name: Android Build (APK)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Gradle 7.6
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 7.6

      - name: Grant execute permission for gradlew
        run: chmod +x ./android/gradlew

      - name: Build Release APK
        working-directory: ./android
        run: ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk 