name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Run gradle plugin fix script
        run: node fix-react-native-gradle-plugin.js

      - name: Print gradle plugin file (debug)
        run: |
          tail -n 20 node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/build.gradle.kts || cat node_modules/@react-native/gradle-plugin/react-native-gradle-plugin/build.gradle.kts

      - name: Make gradlew executable
        run: chmod +x android/gradlew

      - name: Build APK
        run: cd android && ./gradlew assembleRelease

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk 