name: Quick Android Build

on:
  workflow_dispatch:
    inputs:
      build_type:
        description: 'Build Type'
        required: true
        default: 'apk'
        type: choice
        options:
        - apk
        - aab
        - both

jobs:
  quick-build:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
        
    - name: Cache Gradle packages
      uses: actions/cache@v3
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
          
    - name: Grant execute permission for gradlew
      run: chmod +x android/gradlew
      
    - name: Clean Android build
      run: |
        cd android
        ./gradlew clean
        cd ..
        
    - name: Build APK
      if: ${{ github.event.inputs.build_type == 'apk' || github.event.inputs.build_type == 'both' }}
      run: |
        cd android
        ./gradlew assembleRelease --no-daemon --stacktrace
        cd ..
        
    - name: Build AAB
      if: ${{ github.event.inputs.build_type == 'aab' || github.event.inputs.build_type == 'both' }}
      run: |
        cd android
        ./gradlew bundleRelease --no-daemon --stacktrace
        cd ..
        
    - name: Upload APK
      if: ${{ github.event.inputs.build_type == 'apk' || github.event.inputs.build_type == 'both' }}
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: android/app/build/outputs/apk/release/app-release.apk
        
    - name: Upload AAB
      if: ${{ github.event.inputs.build_type == 'aab' || github.event.inputs.build_type == 'both' }}
      uses: actions/upload-artifact@v3
      with:
        name: app-release-aab
        path: android/app/build/outputs/bundle/release/app-release.aab
